### ISSUE TITLE
Support for 3.x

### ISSUE THREAD

**Issue by adam-bergstein** [drutiny/project-dev#6]
Is there a plan to have this support Drutiny 3.x? 

When running `composer create-project --no-interaction --prefer-source -s dev drutiny/project-dev drutiny-dev`, it shows 2.4.x

**Comment by fiasco** [comment]
I'm not sure TBH. Apart of me thinks I should just EOL it to minimize upkeep overheads in place of just good documentation. Since the initial creation of this project, I had started rolling phar files that might be the preferable alternative to this approach.
